import { SiteSettings } from "@/src/types";

export const DEFAULT_SETTINGS: SiteSettings = {
  siteName: { value: "Penstack", enabled: true, encrypted: false },
  siteDescription: { value: "", enabled: true, encrypted: false },
  siteOpengraph: { value: "", enabled: true, encrypted: false },
  siteLogo: { value: "", enabled: true, encrypted: false },
  siteLogoMobile: { value: "", enabled: true, encrypted: false },
  siteFavicon: { value: "", enabled: true, encrypted: false },
  maintenanceMode: { value: "false", enabled: false, encrypted: false },
  gaId: { value: "", enabled: false, encrypted: false },
  gtmId: { value: "", enabled: false, encrypted: false },
  mixpanelToken: { value: "", enabled: false, encrypted: false },
  posthogKey: { value: "", enabled: false, encrypted: false },
  posthogHost: {
    value: "https://app.posthog.com",
    enabled: false,
    encrypted: false,
  },
  sentryDsn: { value: "", enabled: false, encrypted: false },
  sentryEnvironment: { value: "production", enabled: false, encrypted: false },
  errorTracking: { value: "false", enabled: false, encrypted: false },
  performanceMonitoring: { value: "false", enabled: false, encrypted: false },
  cloudinaryName: { value: "", enabled: false, encrypted: false },
  maxUploadSize: { value: "10", enabled: true, encrypted: false },
  defaultMediaFolder: { value: "uploads", enabled: true, encrypted: false },
  apiRateLimit: { value: "100", enabled: true, encrypted: false },
  cacheDuration: { value: "30", enabled: true, encrypted: false },
  emailFrom: { value: "", enabled: true, encrypted: false },
  newsletterEmailFrom: { value: "", enabled: false, encrypted: false },
  emailFromName: { value: "", enabled: true, encrypted: false },
  localPostAnalytics: { value: "", enabled: false, encrypted: false },
  showSiteNameWithLogo: { value: "", enabled: false, encrypted: false },
  codeInjectionHead: { value: "", enabled: false, encrypted: false },
  codeInjectionFoot: { value: "", enabled: false, encrypted: false },
};
