import { SiteSettings } from "@/types";

export const DEFAULT_SETTINGS: SiteSettings = {
  siteName: {
    value: "Penstack",
    enabled: true,
    encrypted: false,
    canEncrypt: false,
    folder: "general",
    name: "Site Name",
  },
  siteTitle: {
    value: "Penstack",
    enabled: true,
    encrypted: false,
    canEncrypt: false,
    folder: "general",
    name: "Site Title",
    description:
      "The title of the site displayed in the browser and search engines",
  },
  siteDescription: {
    value:
      "Penstack is a modern, clean, minimalistic and customizable nextjs blog",
    enabled: true,
    encrypted: false,
    canEncrypt: false,
    folder: "general",
    name: "Site Description",
  },
  siteOpengraph: {
    value: "",
    enabled: true,
    encrypted: false,
    canEncrypt: false,
    folder: "general",
    name: "Site Opengraph Image",
    description: "The opengraph image of the site",
  },
  siteLogo: {
    value: "",
    enabled: true,
    encrypted: false,
    canEncrypt: false,
    folder: "general",
    name: "Site Logo",
    description: "The logo of the site - (Recommended size 128x128)",
  },
  siteLogoMobile: {
    value: "",
    enabled: true,
    encrypted: false,
    canEncrypt: false,
    folder: "general",
    name: "Site Logo Mobile",
    description: "The logo of the site for mobile devices",
  },
  siteFavicon: {
    value: "",
    enabled: true,
    encrypted: false,
    canEncrypt: false,
    folder: "general",
    name: "Site Favicon",
    description: "The favicon of the site - (Recommended size 32x32)",
  },
  maintenanceMode: {
    value: "false",
    enabled: false,
    encrypted: false,
    canEncrypt: false,
    folder: "misc",
    name: "Maintenance Mode",
    description: "Turn on/off maintenance mode",
  },
  gaId: {
    value: "",
    enabled: false,
    encrypted: false,
    canEncrypt: false,
    folder: "analytics",
    name: "Google Analytics ID",
    description: "The Google Analytics Measurement ID",
  },
  gtmId: {
    value: "",
    enabled: false,
    encrypted: false,
    canEncrypt: false,
    folder: "analytics",
    name: "Google Tag Manager ID",
  },
  mixpanelToken: {
    value: "",
    enabled: false,
    encrypted: false,
    canEncrypt: false,
    folder: "analytics",
    name: "Mixpanel Token",
  },
  posthogKey: {
    value: "",
    enabled: false,
    encrypted: false,
    canEncrypt: true,
    folder: "analytics",
    name: "Posthog Key",
  },
  posthogHost: {
    value: "https://app.posthog.com",
    enabled: false,
    encrypted: false,
    canEncrypt: false,
    folder: "analytics",
    name: "Posthog Host",
  },
  sentryDsn: {
    value: "",
    enabled: false,
    encrypted: false,
    canEncrypt: false,
    folder: "monitoring",
    name: "Sentry DSN",
  },
  sentryEnvironment: {
    value: "",
    enabled: false,
    encrypted: false,
    canEncrypt: false,
    folder: "monitoring",
    name: "Sentry Environment",
    description: "The environment of the sentry project",
  },
  errorTracking: {
    value: "false",
    enabled: false,
    encrypted: false,
    canEncrypt: false,
    folder: "monitoring",
    name: "Error Tracking",
    description: "Turn on/off error tracking",
  },
  performanceMonitoring: {
    value: "false",
    enabled: false,
    encrypted: false,
    canEncrypt: false,
    folder: "monitoring",
    name: "Performance Monitoring",
  },
  resendApiKey: {
    value: "",
    enabled: false,
    encrypted: false,
    canEncrypt: true,
    folder: "email",
    name: "Resend API Key",
    description: "The API key for the Resend email service",
  },
  cloudinaryCloudName: {
    value: "",
    enabled: true,
    encrypted: false,
    canEncrypt: false,
    folder: "media",
    name: "Cloudinary Cloud Name",
    description: "The cloud name of the Cloudinary account",
  },
  cloudinaryApiKey: {
    value: "",
    enabled: true,
    encrypted: false,
    canEncrypt: false,
    folder: "media",
    name: "Cloudinary API Key",
    description: "The API key for the Cloudinary account",
  },
  cloudinaryApiSecret: {
    value: "",
    enabled: true,
    encrypted: false,
    canEncrypt: true,
    folder: "media",
    name: "Cloudinary API Secret",
    description: "The API secret for the Cloudinary account",
  },
  maxUploadSize: {
    value: "10",
    enabled: true,
    encrypted: false,
    canEncrypt: false,
    folder: "media",
    name: "Max Upload Size",
    description: "The maximum upload size in MB",
  },
  defaultMediaFolder: {
    value: "uploads",
    enabled: true,
    encrypted: false,
    canEncrypt: false,
    folder: "media",
    name: "Default Media Folder",
    description: "The default media folder",
  },
  apiRateLimit: {
    value: "100",
    enabled: true,
    encrypted: false,
    canEncrypt: false,
    folder: "advanced",
    name: "API Rate Limit",
    description: "The rate limit for the API",
  },
  cacheDuration: {
    value: "30",
    enabled: true,
    encrypted: false,
    canEncrypt: false,
    folder: "advanced",
    name: "Cache Duration",
    description: "The duration of the cache in minutes",
  },
  emailFrom: {
    value: "",
    enabled: true,
    encrypted: false,
    canEncrypt: false,
    folder: "email",
    name: "Email From",
    description: "The email address to send emails from",
  },
  newsletterEmailFrom: {
    value: "",
    enabled: false,
    encrypted: false,
    canEncrypt: false,
    folder: "email",
    name: "Newsletter Email From",
    description: "The email address to send newsletters from",
  },
  facebook: {
    value: "",
    enabled: false,
    encrypted: false,
    canEncrypt: false,
    folder: "social",
    name: "Facebook",
  },
  twitter: {
    value: "",
    enabled: false,
    encrypted: false,
    canEncrypt: false,
    folder: "social",
    name: "Twitter",
  },
  github: {
    value: "",
    enabled: false,
    encrypted: false,
    canEncrypt: false,
    folder: "social",
    name: "Github",
  },
  linkedin: {
    value: "",
    enabled: false,
    encrypted: false,
    canEncrypt: false,
    folder: "social",
    name: "Linkedin",
  },
  email: {
    value: "",
    enabled: true,
    encrypted: false,
    canEncrypt: false,
    folder: "social",
    name: "Email",
    description: "The contact email address",
  },
  emailFromName: {
    value: "",
    enabled: true,
    encrypted: false,
    canEncrypt: false,
    folder: "email",
    name: "From Name",
    description: "The name of the email sender",
  },
  localPostAnalytics: {
    value: "",
    enabled: false,
    encrypted: false,
    canEncrypt: false,
    folder: "analytics",
    name: "Local Post Analytics",
    description: "Turn on/off local post analytics",
  },
  showSiteNameWithLogo: {
    value: "",
    enabled: false,
    encrypted: false,
    canEncrypt: false,
    folder: "general",
    name: "Show Site Name With Logo",
    description: "Show the site name with the logo",
  },
};
